"""Comprehensive test suite for services.py - Enhanced Phase I.

This test suite validates TodoService class with CRUD operations plus
search, filter, and sort functionality for the enhanced console application.

Generated by: hackathon-test-generator agent
Spec: specs/phase-1/spec.md
Target Coverage: 85%+ for services module
"""

import pytest
from todo_app.models import Priority, Task
from todo_app.services import TodoService


# ========================================
# Fixtures
# ========================================

@pytest.fixture
def service() -> TodoService:
    """Create a fresh TodoService instance for each test.

    Returns:
        Empty TodoService with no tasks
    """
    return TodoService()


@pytest.fixture
def service_with_tasks() -> TodoService:
    """Create TodoService with sample tasks for testing.

    Returns:
        TodoService with 4 pre-populated tasks:
        - ID 1: "Buy groceries" (HIGH, work)
        - ID 2: "Write report" (MEDIUM, work, urgent)
        - ID 3: "Clean house" (LOW, home)
        - ID 4: "Team meeting" (HIGH, work, meeting)
    """
    svc = TodoService()
    svc.add_task("Buy groceries", "Milk and bread", Priority.HIGH, ["work"])
    svc.add_task("Write report", "Q4 financial report", Priority.MEDIUM, ["work", "urgent"])
    svc.add_task("Clean house", "Living room and kitchen", Priority.LOW, ["home"])
    svc.add_task("Team meeting", "Discuss roadmap", Priority.HIGH, ["work", "meeting"])
    return svc


# ========================================
# TodoService.add_task() Tests
# ========================================

class TestAddTask:
    """Tests for TodoService.add_task() method."""

    def test_add_task_creates_task_with_id(self, service: TodoService) -> None:
        """Test that add_task() creates task with auto-generated ID.

        Validates: First task gets ID 1
        """
        task = service.add_task("Buy groceries", "Milk and bread")

        assert task is not None
        assert task.id == 1
        assert task.title == "Buy groceries"
        assert task.description == "Milk and bread"

    def test_add_task_validates_non_empty_title(self, service: TodoService) -> None:
        """Test that add_task() rejects empty title.

        Validates: Empty title raises ValueError
        """
        with pytest.raises(ValueError, match="Title is required"):
            service.add_task("", "Some description")

    def test_add_task_validates_whitespace_only_title(self, service: TodoService) -> None:
        """Test that add_task() rejects whitespace-only title.

        Validates: Whitespace-only title raises ValueError
        """
        with pytest.raises(ValueError, match="Title is required"):
            service.add_task("   ", "Some description")

    def test_add_task_defaults_to_medium_priority(self, service: TodoService) -> None:
        """Test that add_task() defaults to MEDIUM priority.

        Validates: Priority defaults to MEDIUM when not specified
        """
        task = service.add_task("Task", "Description")

        assert task.priority == Priority.MEDIUM

    def test_add_task_accepts_high_priority(self, service: TodoService) -> None:
        """Test that add_task() accepts HIGH priority.

        Validates: HIGH priority can be specified
        """
        task = service.add_task("Urgent task", "Fix ASAP", Priority.HIGH)

        assert task.priority == Priority.HIGH

    def test_add_task_accepts_low_priority(self, service: TodoService) -> None:
        """Test that add_task() accepts LOW priority.

        Validates: LOW priority can be specified
        """
        task = service.add_task("Someday task", "When free", Priority.LOW)

        assert task.priority == Priority.LOW

    def test_add_task_increments_id_sequentially(self, service: TodoService) -> None:
        """Test that add_task() increments IDs sequentially (1, 2, 3).

        Validates: Each new task gets next sequential ID
        """
        task1 = service.add_task("Task 1", "")
        task2 = service.add_task("Task 2", "")
        task3 = service.add_task("Task 3", "")

        assert task1.id == 1
        assert task2.id == 2
        assert task3.id == 3

    def test_add_task_with_empty_description(self, service: TodoService) -> None:
        """Test that add_task() accepts empty description.

        Validates: Description is optional (can be empty)
        """
        task = service.add_task("Task", "")

        assert task.title == "Task"
        assert task.description == ""

    def test_add_task_with_no_tags(self, service: TodoService) -> None:
        """Test that add_task() works with no tags.

        Validates: Tags default to empty list
        """
        task = service.add_task("Task", "Description")

        assert task.tags == []

    def test_add_task_with_single_tag(self, service: TodoService) -> None:
        """Test that add_task() accepts single tag.

        Validates: Single tag can be specified
        """
        task = service.add_task("Task", "Description", Priority.MEDIUM, ["work"])

        assert task.tags == ["work"]

    def test_add_task_with_multiple_tags(self, service: TodoService) -> None:
        """Test that add_task() accepts multiple tags.

        Validates: Multiple tags can be specified
        """
        task = service.add_task("Task", "Description", Priority.HIGH, ["work", "urgent", "meeting"])

        assert task.tags == ["work", "urgent", "meeting"]
        assert len(task.tags) == 3

    def test_add_task_stores_task_in_service(self, service: TodoService) -> None:
        """Test that add_task() stores task in service.

        Validates: Added task appears in get_all_tasks()
        """
        service.add_task("Task", "Description")
        tasks = service.get_all_tasks()

        assert len(tasks) == 1
        assert tasks[0].title == "Task"


# ========================================
# TodoService.get_all_tasks() Tests
# ========================================

class TestGetAllTasks:
    """Tests for TodoService.get_all_tasks() method."""

    def test_get_all_tasks_returns_copy(self, service_with_tasks: TodoService) -> None:
        """Test that get_all_tasks() returns copy of tasks list.

        Validates: Modifying returned list doesn't affect service
        """
        tasks = service_with_tasks.get_all_tasks()
        original_count = len(tasks)

        # Modify the returned list
        tasks.append(Task(id=99, title="Fake", description=""))

        # Original list should be unchanged
        tasks_again = service_with_tasks.get_all_tasks()
        assert len(tasks_again) == original_count

    def test_get_all_tasks_with_empty_service(self, service: TodoService) -> None:
        """Test that get_all_tasks() returns empty list for new service.

        Validates: Empty service returns []
        """
        tasks = service.get_all_tasks()

        assert tasks == []
        assert len(tasks) == 0

    def test_get_all_tasks_returns_all_tasks(self, service_with_tasks: TodoService) -> None:
        """Test that get_all_tasks() returns all tasks.

        Validates: All added tasks are returned
        """
        tasks = service_with_tasks.get_all_tasks()

        assert len(tasks) == 4
        assert tasks[0].title == "Buy groceries"
        assert tasks[1].title == "Write report"
        assert tasks[2].title == "Clean house"
        assert tasks[3].title == "Team meeting"


# ========================================
# TodoService.get_task_by_id() Tests
# ========================================

class TestGetTaskById:
    """Tests for TodoService.get_task_by_id() method."""

    def test_get_task_by_id_finds_task(self, service_with_tasks: TodoService) -> None:
        """Test that get_task_by_id() finds existing task.

        Validates: Valid ID returns correct task
        """
        task = service_with_tasks.get_task_by_id(2)

        assert task is not None
        assert task.id == 2
        assert task.title == "Write report"

    def test_get_task_by_id_returns_none_for_invalid_id(self, service_with_tasks: TodoService) -> None:
        """Test that get_task_by_id() returns None for non-existent ID.

        Validates: Invalid ID returns None
        """
        task = service_with_tasks.get_task_by_id(999)

        assert task is None

    def test_get_task_by_id_with_empty_service(self, service: TodoService) -> None:
        """Test that get_task_by_id() returns None for empty service.

        Validates: No tasks means None for any ID
        """
        task = service.get_task_by_id(1)

        assert task is None

    def test_get_task_by_id_finds_first_task(self, service_with_tasks: TodoService) -> None:
        """Test that get_task_by_id() finds ID 1.

        Validates: First task is retrievable
        """
        task = service_with_tasks.get_task_by_id(1)

        assert task is not None
        assert task.id == 1
        assert task.title == "Buy groceries"

    def test_get_task_by_id_finds_last_task(self, service_with_tasks: TodoService) -> None:
        """Test that get_task_by_id() finds last task.

        Validates: Last task is retrievable
        """
        task = service_with_tasks.get_task_by_id(4)

        assert task is not None
        assert task.id == 4
        assert task.title == "Team meeting"


# ========================================
# TodoService.update_task() Tests
# ========================================

class TestUpdateTask:
    """Tests for TodoService.update_task() method."""

    def test_update_task_updates_fields(self, service_with_tasks: TodoService) -> None:
        """Test that update_task() updates title and description.

        Validates: Title and description can be updated
        """
        task = service_with_tasks.update_task(1, "New title", "New description")

        assert task is not None
        assert task.id == 1
        assert task.title == "New title"
        assert task.description == "New description"

    def test_update_task_validates_non_empty_title(self, service_with_tasks: TodoService) -> None:
        """Test that update_task() rejects empty title.

        Validates: Empty title raises ValueError
        """
        with pytest.raises(ValueError, match="Title is required"):
            service_with_tasks.update_task(1, "", "Description")

    def test_update_task_validates_whitespace_only_title(self, service_with_tasks: TodoService) -> None:
        """Test that update_task() rejects whitespace-only title.

        Validates: Whitespace-only title raises ValueError
        """
        with pytest.raises(ValueError, match="Title is required"):
            service_with_tasks.update_task(1, "   ", "Description")

    def test_update_task_returns_none_for_invalid_id(self, service_with_tasks: TodoService) -> None:
        """Test that update_task() returns None for non-existent ID.

        Validates: Invalid ID returns None
        """
        task = service_with_tasks.update_task(999, "Title", "Description")

        assert task is None

    def test_update_task_preserves_id(self, service_with_tasks: TodoService) -> None:
        """Test that update_task() preserves task ID.

        Validates: ID remains unchanged after update
        """
        original_id = 2
        task = service_with_tasks.update_task(original_id, "Updated title", "Updated desc")

        assert task is not None
        assert task.id == original_id

    def test_update_task_updates_only_title(self, service_with_tasks: TodoService) -> None:
        """Test that update_task() can update only title.

        Validates: Description remains unchanged when not provided
        """
        original_task = service_with_tasks.get_task_by_id(1)
        assert original_task is not None
        original_description = original_task.description

        task = service_with_tasks.update_task(1, "New title")

        assert task is not None
        assert task.title == "New title"
        assert task.description == original_description

    def test_update_task_updates_only_description(self, service_with_tasks: TodoService) -> None:
        """Test that update_task() can update only description.

        Validates: Title remains unchanged when not provided
        """
        original_task = service_with_tasks.get_task_by_id(1)
        assert original_task is not None
        original_title = original_task.title

        task = service_with_tasks.update_task(1, description="New description")

        assert task is not None
        assert task.title == original_title
        assert task.description == "New description"


# ========================================
# TodoService.delete_task() Tests
# ========================================

class TestDeleteTask:
    """Tests for TodoService.delete_task() method."""

    def test_delete_task_removes_task(self, service_with_tasks: TodoService) -> None:
        """Test that delete_task() removes task from service.

        Validates: Deleted task no longer in get_all_tasks()
        """
        result = service_with_tasks.delete_task(2)

        assert result is True
        tasks = service_with_tasks.get_all_tasks()
        assert len(tasks) == 3
        assert service_with_tasks.get_task_by_id(2) is None

    def test_delete_task_returns_false_for_invalid_id(self, service_with_tasks: TodoService) -> None:
        """Test that delete_task() returns False for non-existent ID.

        Validates: Invalid ID returns False
        """
        result = service_with_tasks.delete_task(999)

        assert result is False

    def test_delete_task_preserves_other_tasks(self, service_with_tasks: TodoService) -> None:
        """Test that delete_task() doesn't affect other tasks.

        Validates: Other tasks remain after deletion
        """
        service_with_tasks.delete_task(2)

        task1 = service_with_tasks.get_task_by_id(1)
        task3 = service_with_tasks.get_task_by_id(3)
        task4 = service_with_tasks.get_task_by_id(4)

        assert task1 is not None
        assert task3 is not None
        assert task4 is not None

    def test_delete_task_with_empty_service(self, service: TodoService) -> None:
        """Test that delete_task() returns False for empty service.

        Validates: Cannot delete from empty service
        """
        result = service.delete_task(1)

        assert result is False


# ========================================
# TodoService.mark_task_complete() Tests
# ========================================

class TestMarkTaskComplete:
    """Tests for TodoService.mark_task_complete() method."""

    def test_mark_task_complete_toggles_status(self, service_with_tasks: TodoService) -> None:
        """Test that mark_task_complete() toggles completion status.

        Validates: Pending task becomes complete
        """
        task = service_with_tasks.get_task_by_id(1)
        assert task is not None
        assert task.completed is False

        updated_task = service_with_tasks.mark_task_complete(1)

        assert updated_task is not None
        assert updated_task.completed is True

    def test_mark_task_complete_toggles_back_to_pending(self, service_with_tasks: TodoService) -> None:
        """Test that mark_task_complete() toggles complete back to pending.

        Validates: Complete task becomes pending
        """
        # First toggle to complete
        service_with_tasks.mark_task_complete(1)

        # Second toggle back to pending
        task = service_with_tasks.mark_task_complete(1)

        assert task is not None
        assert task.completed is False

    def test_mark_task_complete_returns_none_for_invalid_id(self, service_with_tasks: TodoService) -> None:
        """Test that mark_task_complete() returns None for non-existent ID.

        Validates: Invalid ID returns None
        """
        task = service_with_tasks.mark_task_complete(999)

        assert task is None


# ========================================
# TodoService.search_tasks() Tests
# ========================================

class TestSearchTasks:
    """Tests for TodoService.search_tasks() method."""

    def test_search_tasks_finds_matches(self, service_with_tasks: TodoService) -> None:
        """Test that search_tasks() finds tasks matching keyword.

        Validates: Keyword "report" matches task with "report" in title
        """
        results = service_with_tasks.search_tasks("report")

        assert len(results) == 1
        assert results[0].title == "Write report"

    def test_search_tasks_case_insensitive(self, service_with_tasks: TodoService) -> None:
        """Test that search_tasks() is case-insensitive.

        Validates: "GROCERIES" matches "Buy groceries"
        """
        results = service_with_tasks.search_tasks("GROCERIES")

        assert len(results) == 1
        assert results[0].title == "Buy groceries"

    def test_search_tasks_in_description(self, service_with_tasks: TodoService) -> None:
        """Test that search_tasks() searches in description.

        Validates: Keyword in description is found
        """
        results = service_with_tasks.search_tasks("Q4")

        assert len(results) == 1
        assert results[0].title == "Write report"

    def test_search_tasks_returns_empty_for_no_match(self, service_with_tasks: TodoService) -> None:
        """Test that search_tasks() returns empty list for no match.

        Validates: No false positives
        """
        results = service_with_tasks.search_tasks("nonexistent")

        assert results == []

    def test_search_tasks_returns_multiple_matches(self, service_with_tasks: TodoService) -> None:
        """Test that search_tasks() returns all matching tasks.

        Validates: Multiple matches are all returned
        """
        # "work" tag is in 3 tasks
        service_with_tasks.add_task("Another work task", "Description", tags=["work"])

        results = service_with_tasks.search_tasks("work")

        # Should find tasks with "work" in title or description
        assert len(results) >= 1

    def test_search_tasks_with_empty_keyword(self, service_with_tasks: TodoService) -> None:
        """Test that search_tasks() with empty keyword returns all tasks.

        Validates: Empty keyword matches all
        """
        results = service_with_tasks.search_tasks("")

        assert len(results) == 4


# ========================================
# TodoService.filter_by_status() Tests
# ========================================

class TestFilterByStatus:
    """Tests for TodoService.filter_by_status() method."""

    def test_filter_by_status_filters_correctly(self, service_with_tasks: TodoService) -> None:
        """Test that filter_by_status() filters by completion status.

        Validates: completed=False returns only pending tasks
        """
        # All tasks start as pending
        results = service_with_tasks.filter_by_status(completed=False)

        assert len(results) == 4

    def test_filter_by_status_finds_completed_tasks(self, service_with_tasks: TodoService) -> None:
        """Test that filter_by_status() finds completed tasks.

        Validates: completed=True returns only complete tasks
        """
        # Mark one task complete
        service_with_tasks.mark_task_complete(1)

        results = service_with_tasks.filter_by_status(completed=True)

        assert len(results) == 1
        assert results[0].id == 1

    def test_filter_by_status_returns_empty_when_no_matches(self, service_with_tasks: TodoService) -> None:
        """Test that filter_by_status() returns empty list when no matches.

        Validates: No completed tasks returns []
        """
        results = service_with_tasks.filter_by_status(completed=True)

        assert results == []

    def test_filter_by_status_with_mixed_statuses(self, service_with_tasks: TodoService) -> None:
        """Test that filter_by_status() works with mixed statuses.

        Validates: Correctly separates pending and complete tasks
        """
        # Mark tasks 1 and 3 complete
        service_with_tasks.mark_task_complete(1)
        service_with_tasks.mark_task_complete(3)

        pending = service_with_tasks.filter_by_status(completed=False)
        complete = service_with_tasks.filter_by_status(completed=True)

        assert len(pending) == 2
        assert len(complete) == 2


# ========================================
# TodoService.filter_by_priority() Tests
# ========================================

class TestFilterByPriority:
    """Tests for TodoService.filter_by_priority() method."""

    def test_filter_by_priority_filters_correctly(self, service_with_tasks: TodoService) -> None:
        """Test that filter_by_priority() filters by priority level.

        Validates: Priority.HIGH returns only high-priority tasks
        """
        results = service_with_tasks.filter_by_priority(Priority.HIGH)

        assert len(results) == 2
        assert all(task.priority == Priority.HIGH for task in results)

    def test_filter_by_priority_finds_medium(self, service_with_tasks: TodoService) -> None:
        """Test that filter_by_priority() finds MEDIUM priority tasks.

        Validates: Priority.MEDIUM filter works
        """
        results = service_with_tasks.filter_by_priority(Priority.MEDIUM)

        assert len(results) == 1
        assert results[0].title == "Write report"

    def test_filter_by_priority_finds_low(self, service_with_tasks: TodoService) -> None:
        """Test that filter_by_priority() finds LOW priority tasks.

        Validates: Priority.LOW filter works
        """
        results = service_with_tasks.filter_by_priority(Priority.LOW)

        assert len(results) == 1
        assert results[0].title == "Clean house"

    def test_filter_by_priority_returns_empty_when_no_matches(self, service: TodoService) -> None:
        """Test that filter_by_priority() returns empty list when no matches.

        Validates: No tasks of priority returns []
        """
        service.add_task("Task", "Description", Priority.HIGH)

        results = service.filter_by_priority(Priority.LOW)

        assert results == []


# ========================================
# TodoService.filter_by_tag() Tests
# ========================================

class TestFilterByTag:
    """Tests for TodoService.filter_by_tag() method."""

    def test_filter_by_tag_case_insensitive_filter(self, service_with_tasks: TodoService) -> None:
        """Test that filter_by_tag() is case-insensitive.

        Validates: "WORK" matches tasks with "work" tag
        """
        results = service_with_tasks.filter_by_tag("WORK")

        assert len(results) == 3  # 3 tasks have "work" tag

    def test_filter_by_tag_finds_specific_tag(self, service_with_tasks: TodoService) -> None:
        """Test that filter_by_tag() finds tasks with specific tag.

        Validates: "urgent" tag finds correct task
        """
        results = service_with_tasks.filter_by_tag("urgent")

        assert len(results) == 1
        assert results[0].title == "Write report"

    def test_filter_by_tag_returns_empty_when_no_matches(self, service_with_tasks: TodoService) -> None:
        """Test that filter_by_tag() returns empty list when no matches.

        Validates: Non-existent tag returns []
        """
        results = service_with_tags.filter_by_tag("nonexistent")

        assert results == []

    def test_filter_by_tag_with_multiple_tags_on_task(self, service_with_tasks: TodoService) -> None:
        """Test that filter_by_tag() finds tasks with multiple tags.

        Validates: Task with multiple tags can be found by any tag
        """
        # Task 2 has tags ["work", "urgent"]
        by_work = service_with_tasks.filter_by_tag("work")
        by_urgent = service_with_tasks.filter_by_tag("urgent")

        assert any(task.id == 2 for task in by_work)
        assert any(task.id == 2 for task in by_urgent)


# ========================================
# TodoService.sort_by_priority() Tests
# ========================================

class TestSortByPriority:
    """Tests for TodoService.sort_by_priority() method."""

    def test_sort_by_priority_high_medium_low(self, service_with_tasks: TodoService) -> None:
        """Test that sort_by_priority() sorts HIGH → MEDIUM → LOW.

        Validates: Priority sorting order is correct
        """
        results = service_with_tasks.sort_by_priority()

        # First two should be HIGH priority
        assert results[0].priority == Priority.HIGH
        assert results[1].priority == Priority.HIGH

        # Third should be MEDIUM
        assert results[2].priority == Priority.MEDIUM

        # Last should be LOW
        assert results[3].priority == Priority.LOW

    def test_sort_by_priority_preserves_relative_order(self, service_with_tasks: TodoService) -> None:
        """Test that sort_by_priority() preserves order for same priority.

        Validates: Stable sort maintains insertion order for equal priorities
        """
        results = service_with_tasks.sort_by_priority()

        # Both tasks 1 and 4 are HIGH priority
        # They should appear in original order (1 before 4)
        high_priority_tasks = [task for task in results if task.priority == Priority.HIGH]
        assert high_priority_tasks[0].id == 1
        assert high_priority_tasks[1].id == 4

    def test_sort_by_priority_with_empty_service(self, service: TodoService) -> None:
        """Test that sort_by_priority() returns empty list for empty service.

        Validates: Empty service returns []
        """
        results = service.sort_by_priority()

        assert results == []


# ========================================
# TodoService.sort_by_title() Tests
# ========================================

class TestSortByTitle:
    """Tests for TodoService.sort_by_title() method."""

    def test_sort_by_title_a_to_z_case_insensitive(self, service_with_tasks: TodoService) -> None:
        """Test that sort_by_title() sorts A-Z case-insensitive.

        Validates: Alphabetical sorting works
        """
        results = service_with_tasks.sort_by_title()

        # Expected order: Buy, Clean, Team, Write
        assert results[0].title == "Buy groceries"
        assert results[1].title == "Clean house"
        assert results[2].title == "Team meeting"
        assert results[3].title == "Write report"

    def test_sort_by_title_case_insensitive_comparison(self, service: TodoService) -> None:
        """Test that sort_by_title() is case-insensitive.

        Validates: "apple" and "Apple" sort together
        """
        service.add_task("zebra", "")
        service.add_task("Apple", "")
        service.add_task("banana", "")

        results = service.sort_by_title()

        assert results[0].title == "Apple"
        assert results[1].title == "banana"
        assert results[2].title == "zebra"

    def test_sort_by_title_with_empty_service(self, service: TodoService) -> None:
        """Test that sort_by_title() returns empty list for empty service.

        Validates: Empty service returns []
        """
        results = service.sort_by_title()

        assert results == []


# ========================================
# TodoService.sort_by_id() Tests
# ========================================

class TestSortById:
    """Tests for TodoService.sort_by_id() method."""

    def test_sort_by_id_ascending_order(self, service_with_tasks: TodoService) -> None:
        """Test that sort_by_id() sorts in ascending ID order.

        Validates: IDs sort 1, 2, 3, 4
        """
        # Delete task 2 and add new task to create non-sequential order
        service_with_tasks.delete_task(2)
        service_with_tasks.add_task("New task", "")

        results = service_with_tasks.sort_by_id()

        # Should be in ascending ID order
        for i in range(len(results) - 1):
            assert results[i].id < results[i + 1].id

    def test_sort_by_id_with_gaps(self, service_with_tasks: TodoService) -> None:
        """Test that sort_by_id() handles ID gaps from deletions.

        Validates: Sorting works with non-sequential IDs
        """
        # Delete task 2
        service_with_tasks.delete_task(2)

        results = service_with_tasks.sort_by_id()

        # Should have IDs 1, 3, 4 in order
        assert results[0].id == 1
        assert results[1].id == 3
        assert results[2].id == 4

    def test_sort_by_id_with_empty_service(self, service: TodoService) -> None:
        """Test that sort_by_id() returns empty list for empty service.

        Validates: Empty service returns []
        """
        results = service.sort_by_id()

        assert results == []
