openapi: 3.0.3
info:
  title: Todo Chat API
  description: API for AI-powered todo chatbot functionality
  version: 1.0.0
servers:
  - url: https://api.todoapp.com/v1
    description: Production server
  - url: https://staging-api.todoapp.com/v1
    description: Staging server

paths:
  /chat/{user_id}:
    post:
      summary: Send a message to the chatbot
      description: Process a user message through the AI chatbot and return a response
      parameters:
        - name: user_id
          in: path
          required: true
          description: The ID of the user sending the message
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ChatMessageRequest'
      responses:
        '200':
          description: Successful response from the chatbot
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ChatMessageResponse'
        '400':
          description: Invalid request (malformed message, invalid user_id, etc.)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: Unauthorized (invalid or expired token)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '403':
          description: Forbidden (user trying to access another user's data)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '429':
          description: Rate limit exceeded
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
      security:
        - bearerAuth: []

  /chat/{user_id}/conversations:
    get:
      summary: Get user's conversations
      description: Retrieve a list of conversation summaries for the user
      parameters:
        - name: user_id
          in: path
          required: true
          description: The ID of the user
          schema:
            type: string
            format: uuid
        - name: limit
          in: query
          required: false
          description: Maximum number of conversations to return (default: 20, max: 100)
          schema:
            type: integer
            minimum: 1
            maximum: 100
            default: 20
        - name: offset
          in: query
          required: false
          description: Number of conversations to skip (for pagination)
          schema:
            type: integer
            minimum: 0
            default: 0
      responses:
        '200':
          description: List of user's conversations
          content:
            application/json:
              schema:
                type: object
                properties:
                  conversations:
                    type: array
                    items:
                      $ref: '#/components/schemas/ConversationSummary'
                  total_count:
                    type: integer
                  limit:
                    type: integer
                  offset:
                    type: integer
        '401':
          description: Unauthorized (invalid or expired token)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '403':
          description: Forbidden (user trying to access another user's data)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
      security:
        - bearerAuth: []

  /chat/{user_id}/conversations/{conversation_id}:
    get:
      summary: Get conversation messages
      description: Retrieve all messages in a specific conversation
      parameters:
        - name: user_id
          in: path
          required: true
          description: The ID of the user
          schema:
            type: string
            format: uuid
        - name: conversation_id
          in: path
          required: true
          description: The ID of the conversation
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Messages in the conversation
          content:
            application/json:
              schema:
                type: object
                properties:
                  conversation_id:
                    type: string
                    format: uuid
                  title:
                    type: string
                  messages:
                    type: array
                    items:
                      $ref: '#/components/schemas/Message'
        '401':
          description: Unauthorized (invalid or expired token)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '403':
          description: Forbidden (user trying to access another user's conversation)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Conversation not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
      security:
        - bearerAuth: []

    delete:
      summary: Delete a conversation
      description: Permanently delete a conversation and all its messages
      parameters:
        - name: user_id
          in: path
          required: true
          description: The ID of the user
          schema:
            type: string
            format: uuid
        - name: conversation_id
          in: path
          required: true
          description: The ID of the conversation
          schema:
            type: string
            format: uuid
      responses:
        '204':
          description: Conversation successfully deleted
        '401':
          description: Unauthorized (invalid or expired token)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '403':
          description: Forbidden (user trying to delete another user's conversation)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Conversation not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
      security:
        - bearerAuth: []

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    ChatMessageRequest:
      type: object
      required:
        - message
      properties:
        message:
          type: string
          description: The user's message to the chatbot
          minLength: 1
          maxLength: 10000
        conversation_id:
          type: string
          format: uuid
          description: Optional ID of existing conversation (creates new if omitted)
        metadata:
          type: object
          description: Additional metadata for the message
          additionalProperties: true

    ChatMessageResponse:
      type: object
      required:
        - message
        - conversation_id
        - timestamp
      properties:
        message:
          type: string
          description: The chatbot's response to the user
        conversation_id:
          type: string
          format: uuid
          description: The ID of the conversation
        timestamp:
          type: string
          format: date-time
          description: When the response was generated
        action_taken:
          type: string
          description: The action taken by the chatbot (e.g., "task_created", "task_listed")
        confirmation_message:
          type: string
          description: Optional confirmation message for user actions

    Message:
      type: object
      required:
        - id
        - role
        - content
        - timestamp
      properties:
        id:
          type: string
          format: uuid
          description: Unique identifier for the message
        role:
          type: string
          enum: [user, assistant, system]
          description: The role of the message sender
        content:
          type: string
          description: The content of the message
        timestamp:
          type: string
          format: date-time
          description: When the message was created
        metadata:
          type: object
          description: Additional metadata for the message
          additionalProperties: true

    ConversationSummary:
      type: object
      required:
        - id
        - title
        - created_at
        - updated_at
      properties:
        id:
          type: string
          format: uuid
          description: Unique identifier for the conversation
        title:
          type: string
          description: Auto-generated title based on first message or user input
        created_at:
          type: string
          format: date-time
          description: When the conversation was created
        updated_at:
          type: string
          format: date-time
          description: When the conversation was last updated

    ErrorResponse:
      type: object
      required:
        - error
        - message
      properties:
        error:
          type: string
          description: Error code
        message:
          type: string
          description: Human-readable error message
        details:
          type: object
          description: Additional error details (optional)
          additionalProperties: true