openapi: 3.0.3
info:
  title: Phase 3 Chatbot API - DRAFT
  description: DRAFT – Phase 3 Iteration 1 - API specification for the chatbot enhancement to the todo application
  version: 0.1.0-draft
servers:
  - url: http://localhost:8000
    description: Development server
paths:
  /chat:
    post:
      summary: Process chat message and return AI response
      description: Handles a chat message from the user and returns the AI's response using conversation context and MCP tools
      tags:
        - Chat
      security:
        - CookieAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                message:
                  type: string
                  description: The user's message
                conversation_id:
                  type: string
                  format: uuid
                  description: Optional existing conversation ID
              required:
                - message
      responses:
        '200':
          description: Streaming response from the AI
          content:
            text/event-stream:
              schema:
                type: string
                description: Server-sent events stream of AI response
        '401':
          description: Unauthorized - Invalid session
        '422':
          description: Validation error

components:
  securitySchemes:
    CookieAuth:
      type: apiKey
      in: cookie
      name: auth_token
      description: Cookie-based session authentication (HttpOnly cookie automatically included by browser)