openapi: 3.0.0
info:
  title: Chat API for Todo Application
  version: 1.0.0
  description: API for chat interface integration with ChatKit and MCP tools

paths:
  /chat/{user_id}:
    post:
      summary: Send a message to the chatbot
      parameters:
        - name: user_id
          in: path
          required: true
          schema:
            type: string
          description: ID of the authenticated user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                message:
                  type: string
                  description: The user's message
                conversation_id:
                  type: string
                  description: Optional conversation ID to continue existing conversation
              required:
                - message
      responses:
        '200':
          description: Successful response from the chatbot
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ChatMessageResponse'
        '400':
          description: Invalid request
        '401':
          description: Unauthorized
        '500':
          description: Internal server error

    get:
      summary: Get user's conversations
      parameters:
        - name: user_id
          in: path
          required: true
          schema:
            type: string
          description: ID of the authenticated user
        - name: limit
          in: query
          schema:
            type: integer
            default: 20
          description: Number of conversations to return
        - name: offset
          in: query
          schema:
            type: integer
            default: 0
          description: Offset for pagination
      responses:
        '200':
          description: List of user's conversations
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetConversationsResponse'
        '401':
          description: Unauthorized
        '500':
          description: Internal server error

  /chat/{user_id}/conversations/{conversation_id}:
    get:
      summary: Get messages from a specific conversation
      parameters:
        - name: user_id
          in: path
          required: true
          schema:
            type: string
        - name: conversation_id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Messages in the conversation
          content:
            application/json:
              schema:
                type: object
                properties:
                  conversation_id:
                    type: string
                  title:
                    type: string
                  messages:
                    type: array
                    items:
                      $ref: '#/components/schemas/Message'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden - conversation doesn't belong to user
        '404':
          description: Conversation not found
        '500':
          description: Internal server error

    delete:
      summary: Delete a conversation
      parameters:
        - name: user_id
          in: path
          required: true
          schema:
            type: string
        - name: conversation_id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Conversation deleted successfully
        '401':
          description: Unauthorized
        '403':
          description: Forbidden - conversation doesn't belong to user
        '404':
          description: Conversation not found
        '500':
          description: Internal server error

  /api/mcp/tools/invoke:
    post:
      summary: Invoke an MCP tool
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                tool_name:
                  type: string
                  description: Name of the tool to invoke
                parameters:
                  type: object
                  description: Parameters for the tool
                provider:
                  type: string
                  description: Optional provider to use
              required:
                - tool_name
                - parameters
      responses:
        '200':
          description: Tool invocation result
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InvokeToolResponse'
        '401':
          description: Unauthorized
        '500':
          description: Internal server error

  /api/mcp/tools/available:
    get:
      summary: Get list of available MCP tools
      responses:
        '200':
          description: List of available tools
          content:
            application/json:
              schema:
                type: object
                properties:
                  tools:
                    type: array
                    items:
                      $ref: '#/components/schemas/ToolInfo'
        '401':
          description: Unauthorized
        '500':
          description: Internal server error

components:
  schemas:
    Message:
      type: object
      properties:
        id:
          type: string
        role:
          type: string
          enum: [user, assistant]
        content:
          type: string
        timestamp:
          type: string
          format: date-time
        message_metadata:
          type: string
      required:
        - id
        - role
        - content
        - timestamp

    ChatMessageResponse:
      type: object
      properties:
        message:
          type: string
        conversation_id:
          type: string
        timestamp:
          type: string
          format: date-time
        action_taken:
          type: string
        confirmation_message:
          type: string
      required:
        - message
        - conversation_id
        - timestamp
        - action_taken
        - confirmation_message

    ConversationSummary:
      type: object
      properties:
        id:
          type: string
        title:
          type: string
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time

    GetConversationsResponse:
      type: object
      properties:
        conversations:
          type: array
          items:
            $ref: '#/components/schemas/ConversationSummary'
        total_count:
          type: integer
        limit:
          type: integer
        offset:
          type: integer
      required:
        - conversations
        - total_count
        - limit
        - offset

    InvokeToolResponse:
      type: object
      properties:
        success:
          type: boolean
        result:
          type: object
        error:
          type: string
        tool_name:
          type: string
        provider:
          type: string
      required:
        - success
        - tool_name
        - provider

    ToolInfo:
      type: object
      properties:
        name:
          type: string
        description:
          type: string
        provider:
          type: string
        has_access:
          type: boolean
      required:
        - name
        - description
        - provider
        - has_access