"""Comprehensive test suite for models.py - Enhanced Phase I.

This test suite validates Priority enum, Task dataclass with search methods,
and ensures production-ready coverage for all model functionality.

Generated by: hackathon-test-generator agent
Spec: specs/phase-1/spec.md
Target Coverage: 90%+ for models module
"""

import pytest
from todo_app.models import Priority, Task


# ========================================
# Priority Enum Tests
# ========================================

class TestPriorityEnum:
    """Tests for Priority enum values and comparison operations."""

    def test_priority_enum_has_high_value(self) -> None:
        """Test that Priority enum has HIGH value.

        Validates: Priority.HIGH exists and is accessible
        """
        assert hasattr(Priority, 'HIGH')
        assert Priority.HIGH is not None

    def test_priority_enum_has_medium_value(self) -> None:
        """Test that Priority enum has MEDIUM value.

        Validates: Priority.MEDIUM exists and is accessible
        """
        assert hasattr(Priority, 'MEDIUM')
        assert Priority.MEDIUM is not None

    def test_priority_enum_has_low_value(self) -> None:
        """Test that Priority enum has LOW value.

        Validates: Priority.LOW exists and is accessible
        """
        assert hasattr(Priority, 'LOW')
        assert Priority.LOW is not None

    def test_priority_comparison_high_less_than_medium(self) -> None:
        """Test that Priority.HIGH < Priority.MEDIUM for sorting.

        Validates: __lt__ method allows HIGH to sort before MEDIUM
        """
        assert Priority.HIGH < Priority.MEDIUM, "HIGH should sort before MEDIUM"

    def test_priority_comparison_medium_less_than_low(self) -> None:
        """Test that Priority.MEDIUM < Priority.LOW for sorting.

        Validates: __lt__ method allows MEDIUM to sort before LOW
        """
        assert Priority.MEDIUM < Priority.LOW, "MEDIUM should sort before LOW"

    def test_priority_comparison_high_less_than_low(self) -> None:
        """Test that Priority.HIGH < Priority.LOW for sorting.

        Validates: Transitive property of __lt__
        """
        assert Priority.HIGH < Priority.LOW, "HIGH should sort before LOW"

    def test_priority_ordering_in_sorted_list(self) -> None:
        """Test that priorities sort correctly in ascending order (HIGH → MEDIUM → LOW).

        Validates: Priority ordering works with Python's sorted()
        """
        priorities = [Priority.LOW, Priority.HIGH, Priority.MEDIUM]
        sorted_priorities = sorted(priorities)

        assert sorted_priorities == [Priority.HIGH, Priority.MEDIUM, Priority.LOW], \
            "Priorities should sort as HIGH, MEDIUM, LOW"

    def test_priority_not_less_than_self(self) -> None:
        """Test that priority is not less than itself.

        Validates: __lt__ returns False for same priority
        """
        assert not (Priority.HIGH < Priority.HIGH)
        assert not (Priority.MEDIUM < Priority.MEDIUM)
        assert not (Priority.LOW < Priority.LOW)

    def test_priority_medium_not_less_than_high(self) -> None:
        """Test that Priority.MEDIUM is not less than Priority.HIGH.

        Validates: __lt__ comparison direction is correct
        """
        assert not (Priority.MEDIUM < Priority.HIGH), "MEDIUM should not be < HIGH"

    def test_priority_low_not_less_than_medium(self) -> None:
        """Test that Priority.LOW is not less than Priority.MEDIUM.

        Validates: __lt__ comparison direction is correct
        """
        assert not (Priority.LOW < Priority.MEDIUM), "LOW should not be < MEDIUM"


# ========================================
# Task Dataclass Tests
# ========================================

class TestTaskCreation:
    """Tests for Task dataclass creation and field defaults."""

    def test_task_creation_with_all_fields(self) -> None:
        """Test creating a Task with all fields specified.

        Validates: Task dataclass accepts all parameters
        """
        task = Task(
            id=1,
            title="Write report",
            description="Q4 financial report",
            completed=False,
            priority=Priority.HIGH,
            tags=["work", "urgent"]
        )

        assert task.id == 1
        assert task.title == "Write report"
        assert task.description == "Q4 financial report"
        assert task.completed is False
        assert task.priority == Priority.HIGH
        assert task.tags == ["work", "urgent"]

    def test_task_creation_with_defaults(self) -> None:
        """Test creating a Task with default values.

        Validates: Default values - completed=False, priority=MEDIUM, tags=[]
        """
        task = Task(id=2, title="Buy groceries", description="Milk and bread")

        assert task.id == 2
        assert task.title == "Buy groceries"
        assert task.description == "Milk and bread"
        assert task.completed is False, "completed should default to False"
        assert task.priority == Priority.MEDIUM, "priority should default to MEDIUM"
        assert task.tags == [], "tags should default to empty list"

    def test_task_creation_with_empty_description(self) -> None:
        """Test creating a Task with empty description.

        Validates: Empty description is allowed
        """
        task = Task(id=3, title="Call dentist", description="")

        assert task.title == "Call dentist"
        assert task.description == ""
        assert task.completed is False

    def test_task_creation_with_high_priority(self) -> None:
        """Test creating a Task with HIGH priority.

        Validates: Priority.HIGH can be assigned
        """
        task = Task(id=4, title="Emergency fix", description="", priority=Priority.HIGH)

        assert task.priority == Priority.HIGH

    def test_task_creation_with_low_priority(self) -> None:
        """Test creating a Task with LOW priority.

        Validates: Priority.LOW can be assigned
        """
        task = Task(id=5, title="Clean garage", description="", priority=Priority.LOW)

        assert task.priority == Priority.LOW

    def test_task_creation_with_single_tag(self) -> None:
        """Test creating a Task with one tag.

        Validates: Tags list can contain single tag
        """
        task = Task(id=6, title="Review code", description="", tags=["work"])

        assert task.tags == ["work"]
        assert len(task.tags) == 1

    def test_task_creation_with_multiple_tags(self) -> None:
        """Test creating a Task with multiple tags.

        Validates: Tags list can contain multiple tags
        """
        task = Task(id=7, title="Team meeting", description="", tags=["work", "meeting", "weekly"])

        assert task.tags == ["work", "meeting", "weekly"]
        assert len(task.tags) == 3


# ========================================
# Task.matches_keyword() Tests
# ========================================

class TestTaskMatchesKeyword:
    """Tests for Task.matches_keyword() method - case-insensitive search."""

    def test_matches_keyword_in_title_exact_case(self) -> None:
        """Test that matches_keyword() finds exact case match in title.

        Validates: Keyword matching works with exact case
        """
        task = Task(id=1, title="Buy groceries", description="Milk and bread")

        assert task.matches_keyword("groceries") is True

    def test_matches_keyword_in_title_case_insensitive(self) -> None:
        """Test that matches_keyword() is case-insensitive in title.

        Validates: Keyword "GROCERIES" matches title "Buy groceries"
        """
        task = Task(id=1, title="Buy groceries", description="Milk and bread")

        assert task.matches_keyword("GROCERIES") is True
        assert task.matches_keyword("buy") is True
        assert task.matches_keyword("BUY") is True

    def test_matches_keyword_in_description_exact_case(self) -> None:
        """Test that matches_keyword() finds exact case match in description.

        Validates: Keyword matching works in description field
        """
        task = Task(id=2, title="Shopping", description="Milk and bread")

        assert task.matches_keyword("Milk") is True
        assert task.matches_keyword("bread") is True

    def test_matches_keyword_in_description_case_insensitive(self) -> None:
        """Test that matches_keyword() is case-insensitive in description.

        Validates: Keyword "MILK" matches description "Milk and bread"
        """
        task = Task(id=2, title="Shopping", description="Milk and bread")

        assert task.matches_keyword("milk") is True
        assert task.matches_keyword("MILK") is True
        assert task.matches_keyword("BREAD") is True

    def test_matches_keyword_partial_match_in_title(self) -> None:
        """Test that matches_keyword() finds partial matches in title.

        Validates: Substring matching works (e.g., "grocer" in "groceries")
        """
        task = Task(id=3, title="Buy groceries", description="")

        assert task.matches_keyword("grocer") is True
        assert task.matches_keyword("eries") is True

    def test_matches_keyword_partial_match_in_description(self) -> None:
        """Test that matches_keyword() finds partial matches in description.

        Validates: Substring matching works in description
        """
        task = Task(id=4, title="Task", description="Financial report for Q4")

        assert task.matches_keyword("Financial") is True
        assert task.matches_keyword("report") is True
        assert task.matches_keyword("Q4") is True

    def test_matches_keyword_returns_false_for_no_match(self) -> None:
        """Test that matches_keyword() returns False when keyword not found.

        Validates: No false positives when keyword doesn't exist
        """
        task = Task(id=5, title="Buy groceries", description="Milk and bread")

        assert task.matches_keyword("urgent") is False
        assert task.matches_keyword("meeting") is False
        assert task.matches_keyword("xyz") is False

    def test_matches_keyword_with_empty_keyword(self) -> None:
        """Test that matches_keyword() handles empty keyword.

        Validates: Empty string matches all tasks (contains semantics)
        """
        task = Task(id=6, title="Any task", description="Any description")

        # Empty string is contained in all strings
        assert task.matches_keyword("") is True

    def test_matches_keyword_with_empty_title_and_description(self) -> None:
        """Test that matches_keyword() works with empty title and description.

        Validates: No crash when searching empty fields
        """
        task = Task(id=7, title="", description="")

        assert task.matches_keyword("test") is False
        assert task.matches_keyword("") is True

    def test_matches_keyword_with_special_characters(self) -> None:
        """Test that matches_keyword() handles special characters.

        Validates: Special characters in title/description/keyword work correctly
        """
        task = Task(id=8, title="Update Q&A section", description="Fix bug #123")

        assert task.matches_keyword("Q&A") is True
        assert task.matches_keyword("#123") is True

    def test_matches_keyword_with_whitespace(self) -> None:
        """Test that matches_keyword() handles whitespace in keyword.

        Validates: Multi-word keywords work
        """
        task = Task(id=9, title="Team meeting notes", description="Discuss project timeline")

        assert task.matches_keyword("Team meeting") is True
        assert task.matches_keyword("project timeline") is True


# ========================================
# Task.has_tag() Tests
# ========================================

class TestTaskHasTag:
    """Tests for Task.has_tag() method - case-insensitive tag matching."""

    def test_has_tag_exact_case_match(self) -> None:
        """Test that has_tag() finds exact case match.

        Validates: Tag matching works with exact case
        """
        task = Task(id=1, title="Task", description="", tags=["work", "urgent"])

        assert task.has_tag("work") is True
        assert task.has_tag("urgent") is True

    def test_has_tag_case_insensitive_match(self) -> None:
        """Test that has_tag() is case-insensitive.

        Validates: Tag "WORK" matches tag "work"
        """
        task = Task(id=2, title="Task", description="", tags=["work", "home"])

        assert task.has_tag("WORK") is True
        assert task.has_tag("Work") is True
        assert task.has_tag("HOME") is True
        assert task.has_tag("Home") is True

    def test_has_tag_returns_false_for_no_match(self) -> None:
        """Test that has_tag() returns False when tag not in list.

        Validates: No false positives for missing tags
        """
        task = Task(id=3, title="Task", description="", tags=["work"])

        assert task.has_tag("home") is False
        assert task.has_tag("urgent") is False
        assert task.has_tag("personal") is False

    def test_has_tag_with_empty_tags_list(self) -> None:
        """Test that has_tag() returns False for empty tags list.

        Validates: No match when task has no tags
        """
        task = Task(id=4, title="Task", description="", tags=[])

        assert task.has_tag("work") is False
        assert task.has_tag("any") is False

    def test_has_tag_with_multiple_tags(self) -> None:
        """Test that has_tag() works with multiple tags.

        Validates: All tags can be matched individually
        """
        task = Task(id=5, title="Task", description="", tags=["work", "meeting", "weekly", "urgent"])

        assert task.has_tag("work") is True
        assert task.has_tag("meeting") is True
        assert task.has_tag("weekly") is True
        assert task.has_tag("urgent") is True

    def test_has_tag_with_mixed_case_tags_in_list(self) -> None:
        """Test that has_tag() handles mixed case tags in list.

        Validates: Case-insensitive matching regardless of tag storage case
        """
        task = Task(id=6, title="Task", description="", tags=["Work", "HOME", "Personal"])

        assert task.has_tag("work") is True
        assert task.has_tag("WORK") is True
        assert task.has_tag("home") is True
        assert task.has_tag("personal") is True
        assert task.has_tag("PERSONAL") is True

    def test_has_tag_returns_false_for_partial_match(self) -> None:
        """Test that has_tag() does not match partial tags.

        Validates: "wor" does not match "work" (exact tag matching only)
        """
        task = Task(id=7, title="Task", description="", tags=["work", "urgent"])

        assert task.has_tag("wor") is False
        assert task.has_tag("urg") is False
        assert task.has_tag("gent") is False

    def test_has_tag_with_empty_string(self) -> None:
        """Test that has_tag() handles empty string search.

        Validates: Empty string returns False (no empty tags expected)
        """
        task = Task(id=8, title="Task", description="", tags=["work", "home"])

        assert task.has_tag("") is False

    def test_has_tag_with_whitespace_in_tag(self) -> None:
        """Test that has_tag() handles tags with whitespace.

        Validates: Multi-word tags work correctly
        """
        task = Task(id=9, title="Task", description="", tags=["high priority", "work item"])

        assert task.has_tag("high priority") is True
        assert task.has_tag("HIGH PRIORITY") is True
        assert task.has_tag("work item") is True

    def test_has_tag_with_special_characters_in_tag(self) -> None:
        """Test that has_tag() handles special characters.

        Validates: Tags with special chars (e.g., "Q&A", "#urgent") work
        """
        task = Task(id=10, title="Task", description="", tags=["Q&A", "#urgent", "v2.0"])

        assert task.has_tag("Q&A") is True
        assert task.has_tag("q&a") is True
        assert task.has_tag("#urgent") is True
        assert task.has_tag("v2.0") is True
